#!/bin/sh

find_device() {
	devspec="$1"

	case $devspec in
	LABEL=*)
		col=2
		match=$(echo $devspec | cut -f2 -d=)
		;;
	UUID=*)	col=3
		match=$(echo $devspec | cut -f2 -d=)
		;;
	/*)	dev=$devspec;;
	esac

	if [ -z "$dev" ]; then
		dev=$(
		lsblk -lp -o NAME,LABEL,UUID |
		awk -vMATCH=$match -vCOL=$col '$COL == MATCH {print $1}'
		)
	fi

	echo $dev
}

devpart=$(find_device $1)

part=$(expr match "$devpart" '.*\([0-9][0-9]*\)$')

device=$(expr match "$devpart" '\(.*[^0-9][0-9][0-9]*\)p[0-9][0-9]*')
if [ -z "$device" ]; then
	device=$(expr match "$devpart" '\(.*[^0-9]\)[0-9][0-9]*')
fi

echo "NOTICE: Attempting to grow $device partition $part." >&2
echo ',+,' | sfdisk -N$part $device
